// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmMzxid7v6c6APBqkoVWCZdZXUaJIJd3U',
    appId: '1:597764858719:web:5992422529d6d043c74cea',
    messagingSenderId: '597764858719',
    projectId: 'darinawbdb',
    authDomain: 'darinawbdb.firebaseapp.com',
    databaseURL: 'https://darinawbdb-default-rtdb.firebaseio.com',
    storageBucket: 'darinawbdb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKar1ov7rM2H_8BLyry8cU2NTRd_djKQM',
    appId: '1:597764858719:android:8b350c300eb04562c74cea',
    messagingSenderId: '597764858719',
    projectId: 'darinawbdb',
    databaseURL: 'https://darinawbdb-default-rtdb.firebaseio.com',
    storageBucket: 'darinawbdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM6SZe5QD9ySID7cauY-38FobKLdn67rQ',
    appId: '1:597764858719:ios:33cf8e894d697e25c74cea',
    messagingSenderId: '597764858719',
    projectId: 'darinawbdb',
    databaseURL: 'https://darinawbdb-default-rtdb.firebaseio.com',
    storageBucket: 'darinawbdb.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );
}
